import chromium from "@sparticuz/chromium";
import { chromium as pw } from "playwright-core";
import { execSync } from "child_process";
import fs from "fs";
execSync(`psql postgres://ln:ln@localhost:5432/labelnova -qc "delete from rate_limits"`);
const B = "http://localhost:3000";
const b = await pw.launch({ executablePath: await chromium.executablePath(), args: chromium.args });
const p = await (await b.newContext({ reducedMotion: "reduce" })).newPage();
let captured = null;
p.on("request", (r) => { if (r.method() === "POST" && r.headers()["next-action"]) captured = { url: r.url(), headers: r.headers(), body: r.postData() }; });
await p.goto(B + "/login"); await p.getByLabel("Email").fill("hm621496@gmail.com"); await p.getByLabel("Password", { exact: true }).fill("LocalOnlyTestPw-123");
await p.getByRole("button", { name: "Sign in" }).click(); await p.waitForURL((u) => u.pathname === "/admin", { timeout: 10000 });
await p.goto(B + "/admin/users/new");
await p.getByLabel("Full name").fill("Captured Probe"); await p.getByLabel("Email").fill("probe2@x.test");
await p.getByLabel("Role").selectOption("CLIENT"); await p.getByLabel("Password").fill("ProbePass-2026");
const [resp] = await Promise.all([p.waitForResponse((r) => r.request().headers()["next-action"] !== undefined), p.getByRole("button", { name: "Create account" }).click()]);
const text = "(navigated)";
fs.writeFileSync("/tmp/captured-action.json", JSON.stringify({ ...captured, sampleResponse: text }, null, 1));
console.log("url:", captured.url, "\nheaders:", Object.keys(captured.headers).join(", "), "\nbody:", captured.body.slice(0, 200), "\nresponse:", text.slice(0, 300));
await b.close();
